---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  chef_omnibus_url: https://www.chef.io/chef/install.sh
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-6.7

suites:
  - name: nwea
    run_list:
      - recipe[sudo::default]
      - recipe[yum::default]
      - recipe[nginx_nwea::default]
      - recipe[nginx_nwea::nginx]
      - recipe[nginx_nwea::users]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
