source 'https://api.chef.io/organizations/pinn_systems'

metadata

cookbook 'yum', '~> 4.1.0'
cookbook 'chef-sugar', '~> 3.4.0'
cookbook 'php', '~> 1.5.0'
cookbook 'apache2', '~> 3.2.2'
cookbook 'nginx_nwea', '~> 2.99.0'


